# MONGODB_URI='mongodb://localhost:27017/mydb'
# MONGODB_URI='mongodb://mongodb:27017/mydb?authSource=admin&directConnection=true&replicaSet=null&retryWrites=true'

services:
  mongo:
    image: mongo
    restart: always
    container_name: mongodb
    # rootユーザーとか色々すると、authエラーがでる
    # docker compose exec mongo mongosh -u root -p root_password --authenticationDatabase admin
    # environment:
    #   MONGO_INITDB_DATABASE: mydb
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: root_password
    ports:
      - 27017:27017
    volumes:
      - db-data:/data/db
      - ./mongodb/initdb.d:/docker-entrypoint-initdb.d/initdb.d
      # - ./configdb:/data/configdb

  mongo-express:
    image: mongo-express
    container_name: mongogui
    restart: always
    ports:
      - 8081:8081
    environment:
      # ME_CONFIG_MONGODB_ADMINUSERNAME: root
      # ME_CONFIG_MONGODB_ADMINPASSWORD: root_password
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: pass
    depends_on:
      - mongo

volumes:
  db-data:
