version: "3"

services:
  db:
    image: mysql:latest
    container_name: nodeprj
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: myuser
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: nodeprj
      TZ: "Asia/Tokyo"
    ports:
      - "3006:3306"
    networks:
      - my-network
    volumes:
      - ./mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_for_node
    depends_on:
      - db
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=myuser
      - PMA_PASSWORD=password
    ports:
      - "8081:80"
    restart: always
    networks:
      - my-network

volumes:
  mysql-nextjs:

networks:
  my-network:
