version: "3.1"

services:
  mongo:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    hostname: mongo-primary
    container_name: mongodb
    environment:
      MONGO_INITDB_DATABASE: mydb
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      # MONGODB_REPLICA_SET_MODE: primary
      # MONGODB_REPLICA_SET_KEY: replicasetkey123
    ports:
      - 27017:27017
    expose:
      - 27017
    volumes:
      - ./db-data/db-data:/data/db
      - ./configdb:/data/configdb
      # 初期化スクリプトの配置
      - ./etc/init/:/docker-entrypoint-initdb.d/:ro
    entrypoint: ["/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs"]
    depends_on:
      - mongo2
    networks:
      - mongo-database

  mongo2:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    hostname: mongo-secondary
    container_name: mongodb2
    ports:
      - 30001:27017
    expose:
      - 27017
    volumes:
      - ./db-data/db-data2:/data/db
    entrypoint: ["/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs"]
    networks:
      - mongo-database

  mongo-express:
    image: mongo-express
    container_name: mongogui
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: pass
    depends_on:
      - mongo
    networks:
      - mongo-database

networks:
  mongo-database:
